import hashlib
import json
import threading
import time
from collections import OrderedDict
from typing import Any, Dict, List, Optional


class PromptCache:
    """Thread-safe, TTL-based, LRU bounded cache for LLM responses.

    Caching generative output is a deliberate trade: a request with
    `temperature > 0` asks for varied sampling, and returning a stored reply
    gives the same text every time. That is usually the right call for a cost
    gateway — repeat prompts are exactly what should not be paid for twice —
    but it is a product decision, not a technical given, so it is explicit and
    configurable rather than implicit.

    `max_cacheable_temperature` sets where that line sits: requests above it
    bypass the cache entirely. The default of 1.0 preserves the historical
    behaviour of caching everything; set it to 0 to serve only deterministic
    requests from cache.
    """

    def __init__(
        self,
        ttl_seconds: int = 300,
        max_entries: int = 1000,
        max_cacheable_temperature: float = 1.0,
    ):
        self.ttl_seconds = ttl_seconds
        self.max_entries = max_entries
        self.max_cacheable_temperature = max_cacheable_temperature
        self.cache: OrderedDict[str, Dict[str, Any]] = OrderedDict()
        self.lock = threading.Lock()

    def is_cacheable(self, kwargs: Dict[str, Any]) -> bool:
        """Whether this request may be served from / stored in the cache."""
        if kwargs.get("no_cache") or kwargs.get("cache") is False:
            return False
        temperature = kwargs.get("temperature")
        if temperature is None:
            # Unspecified means the backend's own default, which for most
            # chat models is non-zero. Treated as cacheable to preserve the
            # default hit rate; tighten via max_cacheable_temperature.
            return True
        try:
            return float(temperature) <= self.max_cacheable_temperature
        except (TypeError, ValueError):
            return True

    def _generate_key(
        self, messages: List[Dict[str, str]], kwargs: Dict[str, Any]
    ) -> str:
        # Normalize messages
        normalized_messages = [
            {
                "role": str(m.get("role", "")).strip(),
                "content": str(m.get("content", "")).strip(),
            }
            for m in messages
        ]
        # Normalize kwargs (filter out non-comparable values). "model" is
        # included so a request targeting a specific backend never gets
        # served a cached response generated by a different one.
        # "seed" is included because two requests differing only by seed are
        # explicitly asking for different samples; without it they collided on
        # one key and the second silently received the first one's output.
        normalized_kwargs = {
            k: v
            for k, v in kwargs.items()
            if k
            in {
                "model",
                "temperature",
                "max_tokens",
                "top_p",
                "seed",
                "presence_penalty",
                "frequency_penalty",
            }
        }
        serialized = json.dumps(
            {"messages": normalized_messages, "kwargs": normalized_kwargs},
            sort_keys=True,
        )
        return hashlib.sha256(serialized.encode("utf-8")).hexdigest()

    def get(
        self, messages: List[Dict[str, str]], kwargs: Dict[str, Any]
    ) -> Optional[Dict[str, Any]]:
        if not self.is_cacheable(kwargs):
            return None
        key = self._generate_key(messages, kwargs)
        with self.lock:
            if key not in self.cache:
                return None

            entry = self.cache[key]
            # Check TTL expiration
            if time.time() - entry["timestamp"] > self.ttl_seconds:
                del self.cache[key]
                return None

            # Move to end to mark as recently used
            self.cache.move_to_end(key)
            return entry["response"]

    def set(
        self,
        messages: List[Dict[str, str]],
        kwargs: Dict[str, Any],
        response: Dict[str, Any],
    ):
        if not self.is_cacheable(kwargs):
            return
        key = self._generate_key(messages, kwargs)
        with self.lock:
            if key in self.cache:
                self.cache.move_to_end(key)
            self.cache[key] = {"timestamp": time.time(), "response": response}
            # Enforce max capacity eviction (FIFO/LRU eviction of oldest item)
            while len(self.cache) > self.max_entries:
                self.cache.popitem(last=False)

    def clear(self):
        """Clear all cache contents."""
        with self.lock:
            self.cache.clear()
